name: uni_manager
description: "UniManager - Your university life, organized."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    coreLibraryDesugaring: true
    coreLibraryDesugaring("com.android.tools.build:desugaring:2.0.4")
  cupertino_icons: ^1.0.8
  

  # State management
  get: ^4.7.3

  # Local database
  isar_community: ^3.1.0+1
  isar_community_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # Icons
  iconsax: ^0.0.8

  # Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  shared_preferences: ^2.3.3

  # Image picker for profile photo
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # Uncomment and update once you have the Inter font in assets/fonts/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700